{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "basyx-opcua-bridge.fullname" . }}
  labels:
    {{- include "basyx-opcua-bridge.labels" . | nindent 4 }}
{{- end -}}
