apiVersion: v1
kind: Service
metadata:
  name: {{ include "basyx-opcua-bridge.fullname" . }}
  labels:
    {{- include "basyx-opcua-bridge.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: metrics
      port: {{ .Values.service.port }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "basyx-opcua-bridge.selectorLabels" . | nindent 4 }}
